language: cpp

compiler:
    - gcc

before_install:
    - echo $LANG
    - echo $LC_ALL
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq curl g++ gfortran libc6-dev-i386 libatlas-dev libatlas-base-dev libblas-dev liblapack-dev

before_script:
    - export LIBRARY_PATH=/usr/lib/atlas:$LIBRARY_PATH
    - export LD_LIBRARY_PATH=/usr/lib/atlas:$LD_LIBRARY_PATH
    - ls /usr/lib/atlas
    - ls /usr/lib64/atlas
    - mv Makefile.std Makefile

script:
    - ./plink_first_compile
    - make plinkw BLASFLAGS="-L/usr/lib/atlas -llapack -lcblas -latlas" LINKFLAGS="-Wl,-Bdynamic -lm -lpthread -ldl"

notifications:
    email: true

