language: cpp

compiler:
    - gcc

before_install:
    - echo $LANG
    - echo $LC_ALL
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq curl g++ gfortran libc6-dev-i386 libatlas-dev libatlas-base-dev libblas-dev liblapack-dev

before_script:
    - mv Makefile.std Makefile

script:
    - ./plink_first_compile
    - rm plink
    - make plink BLASFLAGS="-L/usr/lib/atlas-base -Wl,-Bstatic -llapack -lcblas -latlas" LINKFLAGS="-Wl,-Bdynamic -lm -lpthread -ldl"

notifications:
    email: true

