language: cpp

compiler:
    - gcc

before_install:
    - echo $LANG
    - echo $LC_ALL
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq curl g++ libc6-dev-i386 libatlas-dev libatlas-base-dev libblas-dev liblapack-dev

before_script:
    - mv Makefile.std Makefile

script:
    - ./plink_first_compile
    - make plinkw

notifications:
    email: true

